### ISSUE TITLE
Roadmap for enhancement

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/racer#829]
Here's a list of functionalities I want to implement in racer.
Please comment anything you think!
### Completion based on trait bounds(#706)
- [x] for `FnArg`
already implemented in #828 
```rust
fn f<T: Clone>(a: T) {
    let b = a.clo~
}
```
- [ ] for struct member
```rust
struct S<T> {
    mem: T
}
fn f<T: Clone>(a: S<T>) {
    let b = a.mem.clo~
}
impl<T: Clone> S<T> {
    fn f(self) {
        let b = a.mem.clo~
    } 
}
```
- [ ] for closures
```rust
fn fun<F: Fn() -> Option<i64>>(f: F) {
    let a = f().unwra~
}
```
### Others
- [ ] closure arguments
```rust
let f = |v: Vec<i64>| {
    v.le~
};
```
- [ ] macros in other crate(related to #777)

- [ ] resolve associated type bounded by type parameter, using real type (thanks to @cynecx !)

```rust
use std::ops::Deref;

struct Foo {}

impl Foo {
    fn bar(&self) {
        println!("nights");
    }
}

struct Ref<'a, T: 'a> {
    obj: &'a T,
}

impl<'a, T> Deref for Ref<'a, T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.obj
    }
}

fn main() {
    let a = Ref { obj: &Foo {} };
    // a. // Auto-complete does not work here
}
```
## Nightly features
- [ ] impl trait([universal_impl_trait](https://doc.rust-lang.org/nightly/unstable-book/language-features/universal-impl-trait.html), [conservative_impl_trait](https://doc.rust-lang.org/nightly/unstable-book/language-features/conservative-impl-trait.html))
- [ ] [dyn_trait](https://doc.rust-lang.org/nightly/unstable-book/language-features/dyn-trait.html)
Currently `dyn` cause parse error in racer, and racer can't complete members in a struct with `dyn`, like
```rust
struct AppHandler {
    name: String,
    app: Box<dyn Application>,
}
```

- [ ] [try_trait](https://doc.rust-lang.org/nightly/unstable-book/library-features/try-trait.html)
- [ ] [extern_in_paths](https://doc.rust-lang.org/nightly/unstable-book/language-features/extern-in-paths.html)
- [ ] [use_nested_groups](https://github.com/rust-lang/rust/issues/44494) (It's stable now!)
- [ ] [crate_visibility_modifier](https://doc.rust-lang.org/unstable-book/language-features/crate-visibility-modifier.html)

Since `syntex-syntax` isn't  maintained now, we need `rustc-ap-syntax` to support these features.

## Misc
- [ ] Union support(#769)
- [ ] loop label support
like
```rust
'label: loop {
    for i in 0..10 {
         if i == 5 {
            break 'lab~
        }
    }
}
```
(Though I don't know anyone need this...)
- [ ] make racer's search flag more specific(#830 )

**Comment by cynecx** [comment]
I am not sure if this is just a bug or it's simply not supported:

```rust
use std::ops::Deref;

struct Foo {}

impl Foo {
    fn bar(&self) {
        println!("nights");
    }
}

struct Ref<'a, T: 'a> {
    obj: &'a T,
}

impl<'a, T> Deref for Ref<'a, T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.obj
    }
}

fn main() {
    let a = Ref { obj: &Foo {} };
    // a. // Auto-complete does not work here
}
```

This doesn't work with rls, but since rls is actually using racer for auto-completion, I assume that it is more appropriate to report this here.

**Comment by kngwyu** [comment]
@cynecx 
If you're pointing out that racer doesn't complete `a.bar()`, it's not a bug.
Now racer doesn't support method completion based on type coercions by `Deref`.
I'm going to add this to roadmap.
Thanks for reporting!

**Comment by kngwyu** [comment]
I decided to support these features in [my branch](https://github.com/kngwyu/racer-nightly) so close this.

**Comment by kngwyu** [comment]
@abbec  
`use_nested_groups` is already supported in my [nightly version](https://github.com/kngwyu/racer-nightly)

**Comment by abbec** [comment]
Trying right now :D

**Comment by abbec** [comment]
Works, awesome ❤️ !

**Comment by Dushistov** [comment]
> use_nested_groups is already supported in my nightly version

@kngwyu Any plans to merge it into racer mainline?

**Comment by kngwyu** [comment]
@Dushistov 
I got push previlege for this repository 2 days ago so I will send a PR soon.
Sorry for delay.
