### ISSUE TITLE
Version 2.2

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/racer#983]
- [ ] trait bound #939 
- [ ] support impl trait
- [ ] get_type command(#730)
- [ ] 2018 style path support(#916, #923)
- [ ] associated type in trait (#784)

**Comment by letmutx** [comment]
I would like to pick impl trait support; Thanks!
